### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by exababy** [Quake1011/Weapon-Restrict#3]
I have disabled all the plugins I use, but I still can't get it to work.

Does the value 0 not work?

For example, can't we ban a weapon completely?

**Comment by csportalsk** [comment]
CSSharp updated to v30 and doesn't work. 
Plugin loaded: [#2]: "Weapon Restrict" (1.1.1) by Quake1011

In readme Config.json line `"RestrictMethod": 2` missing comma.

**Comment by Quake1011** [comment]
> CSSharp updated to v30 and doesn't work. Plugin loaded: [#2]: "Weapon Restrict" (1.1.1) by Quake1011

Hm:\

> In readme Config.json line `"RestrictMethod": 2` missing comma.

Not scared - thats readme :D. But thanks ;)
